<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250123231515 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE evenement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(30) NOT NULL, description TEXT DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE card ALTER id TYPE INT');
        $this->addSql('ALTER TABLE card ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE card ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE "order" ALTER id TYPE INT');
        $this->addSql('ALTER TABLE "order" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE "order" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE order_item ALTER id TYPE INT');
        $this->addSql('ALTER TABLE order_item ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE products ALTER id TYPE INT');
        $this->addSql('ALTER TABLE products ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE products ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE rules ALTER id TYPE INT');
        $this->addSql('ALTER TABLE rules ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE rules ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER id TYPE INT');
        $this->addSql('ALTER TABLE "user" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER available_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER delivered_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE evenement');
        $this->addSql('ALTER TABLE order_item ALTER id TYPE INT');
        $this->addSql('ALTER TABLE order_item ALTER id SET DEFAULT order_item_id_seq');
        $this->addSql('ALTER TABLE order_item ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE products ALTER id TYPE INT');
        $this->addSql('ALTER TABLE products ALTER id SET DEFAULT products_id_seq');
        $this->addSql('ALTER TABLE products ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE "order" ALTER id TYPE INT');
        $this->addSql('ALTER TABLE "order" ALTER id SET DEFAULT order_id_seq');
        $this->addSql('ALTER TABLE "order" ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER id SET DEFAULT messenger_messages_id_seq');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER available_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE messenger_messages ALTER delivered_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE rules ALTER id TYPE INT');
        $this->addSql('ALTER TABLE rules ALTER id SET DEFAULT rules_id_seq');
        $this->addSql('ALTER TABLE rules ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE card ALTER id TYPE INT');
        $this->addSql('ALTER TABLE card ALTER id SET DEFAULT card_id_seq');
        $this->addSql('ALTER TABLE card ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER id TYPE INT');
        $this->addSql('ALTER TABLE "user" ALTER id SET DEFAULT user_id_seq');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
    }
}
