# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    stripe.secret_key: '%env(STRIPE_SECRET_KEY)%'  # Clé secrète Stripe dans .env
    stripe.public_key: '%env(STRIPE_PUBLIC_KEY)%'  # Clé publique Stripe dans .env
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # StripeService : ajouter notre service Stripe ici
    App\Service\StripeService:
        arguments:
            $stripeSecretKey: '%stripe.secret_key%'     # Injecte la clé secrète Stripe depuis .env
            $stripePublicKey: '%stripe.public_key%'     # Injecte la clé publique Stripe depuis .env