# config/services.yaml

parameters:
    stripe.secret_key: '%env(STRIPE_SECRET_KEY)%'  # Clé secrète Stripe dans .env
    stripe.public_key: '%env(STRIPE_PUBLIC_KEY)%'  # Clé publique Stripe dans .env
services:
    # Default service configuration
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances dans tes services.
        autoconfigure: true # Inscrit automatiquement tes services comme commandes, abonnés d'événements, etc.

    # Définir les services dans src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # StripeService : ajouter notre service Stripe ici
    App\Service\StripeService:
        arguments:
            $stripeSecretKey: '%stripe.secret_key%'     # Injecte la clé secrète Stripe depuis .env
            $stripePublicKey: '%stripe.public_key%'     # Injecte la clé publique Stripe depuis .env
